### ISSUE TITLE
Switch Text font

### ISSUE THREAD

**Issue by xuejingzhou** [UCSB-CS56-Projects/cs56-networking-chat#10]
Add a button for users to switch the font for the text, and print a notification to users, telling the current font and size.
---300 points

**Comment by jmangel** [comment]
A button has been added; add dropdowns or popups to select font, size, and maybe color

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
(F16) Appears to be fixed with #27, button changes font/size
