### ISSUE TITLE
Create Public/Private Channels (Rooms)

### ISSUE THREAD

**Issue by xuejingzhou** [UCSB-CS56-Projects/cs56-networking-chat#12]
- Issue: create private chatting room for a group of people the user invites. In the chatting room, it will only display the messages from the users inside the chatting room.

**Comment by alecharrell** [comment]
Approved: ~250

**Comment by dlynch305** [comment]
300 pts*

**Comment by jmangel** [comment]
F16 OK (250 pts)

**Comment by jmangel** [comment]
Closed with #53
