### ISSUE TITLE
Refactor:: Create a LEGIT contactList in server and client

### ISSUE THREAD

**Issue by winterfreddy** [UCSB-CS56-Projects/cs56-networking-chat#31]
Clean up the bogus code, for example the getContacts() method in ClientController.java under controller. Keep in mind that there are other parts of the code that call this bogus method. An example is that JList ContactList in clientWindows.java calls controller.getContacts(), so make sure they fix, not only getContacts, but contactList as well.
~300 pts

**Comment by dlynch305** [comment]
m16 OK

**Comment by jmangel** [comment]
F16 OK (150 pts)

**Comment by jmangel** [comment]
Closed with pull request #48
