### ISSUE TITLE
Refactor:: Make use of observer pattern

### ISSUE THREAD

**Issue by winterfreddy** [ucsb-cs56-projects/cs56-networking-chat#32]
The best and recommended way to do this is use the observer pattern. That way, Controller can connect window classes with method classes using the legit contact list.
~200 pts

**Comment by dlynch305** [comment]
M16 OK

**Comment by jmangel** [comment]
@winterfreddy @dlynch305 can one of you elaborate on what this issue is meant to solve/accomplish? Not clear (to me) what feature of the project this would be refactoring

**Comment by winterfreddy** [comment]
Its meant to fix the issue #35.

**Comment by jmangel** [comment]
F16 OK (150 pts)

**Comment by jleeong** [comment]
@jmangel Can this issue be closed since #35 was already resolved?

**Comment by seemantasaha** [comment]
Closing this issue as the purpose is resolved by #35
