### ISSUE TITLE
Delete user not working (refer to issue #15) 

### ISSUE THREAD

**Issue by winterfreddy** [UCSB-CS56-Projects/cs56-networking-chat#35]
Refer to issue #15.
As of now, the client can delete the user off the list but the list doesn't update correctly- instead of printing out the names of the updated list, it prints out "contact indexNumber" ex) contact02. This method uses the defaultListModel to use remove and will update the contact list. Make sure that the updated contacts list display names not "contact#"
~100 pts

**Comment by dlynch305** [comment]
M16 OK

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed with pull request #48
