### ISSUE TITLE
Create send button on the chat client window

### ISSUE THREAD

**Issue by jleeong** [ucsb-cs56-projects/cs56-networking-chat#45]
Make a 'Send' button on the chat client window when logged in with default behavior to send to broadcast.

**Comment by jmangel** [comment]
I wonder if you should match the functionality of pressing 'Send' to hitting Enter so that it sends to the selected user

**Comment by jmangel** [comment]
F16 OK (50 pts)

**Comment by seemantasaha** [comment]
W18 OK. 50 points.

**Comment by seemantasaha** [comment]
Resolved.
