### ISSUE TITLE
add comments for method and change method name easier to understand

### ISSUE THREAD

**Issue by RityZhang** [UCSB-CS56-Projects/cs56-networking-chat#47]
Estimated 50 points

**Comment by jmangel** [comment]
Can you specify a domain? All files or specific ones (ex. src/client/view/ClientWindow)? 50 points sounds good depending on the scope

**Comment by RityZhang** [comment]
Yes, just for src/client/view/ClientWindow.
Because currently we mainly work on this file.

**Comment by RityZhang** [comment]
150 pts

**Comment by jmangel** [comment]
F16 OK (50 pts)

**Comment by jmangel** [comment]
Closed with PR #52
