### ISSUE TITLE
When close sub-window opened by buttons, all windows including client window will be closed.

### ISSUE THREAD

**Issue by chiisalrdytaken** [ucsb-cs56-projects/cs56-networking-chat#69]
When close sub-window opened by buttons, all windows including client window will be closed. Additionally, the client is still online in the background, and you cannot log in with that client when you try to log in with the username and password. Find a method to fix this issue. Two steps need to be done. Firstly, when we close the subwindows, the client window shouldn't automatically close. Secondly, when we close the client window, we need to ask the user to log out instead of close the window or automatically log the user out.

**Comment by seemantasaha** [comment]
W18 OK for 150 points.

**Comment by seemantasaha** [comment]
Resolved.
